---
title: "Homework 1 Answers (Revision)"
author: "Ellen Tully"
output: 
  tufte::tufte_html:
    css: ../hw.css
    tufte_variant: "envisioned"
    highlight: pygments
link-citations: yes
date: '2022-05-13'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r sort out the packages, include=FALSE}
install.packages("devtools")
devtools::install_github("quinfer/tsfe")
devtools::install_github("avehtari/ROS-Examples", subdir = "rpackage")
```

```{r include = FALSE, include=FALSE}
knitr::opts_chunk$set(
  eval = FALSE,
  out.width = "80%",
  fig.asp = 0.618,
  fig.width = 10
)
library(tidyverse)
library(rosdata)
library(ggrepel)
```

```{r view data and definition, include=FALSE}
View(beauty)
?beauty
```

```{r summarise the number of female professores}
beauty %>%
  summarise("Number of Female Professors"=sum(female))
```

# Exercise Answers

1.  According to the data viewer, there are 463 evaluations.

2.  Again, according to the data viewer, there are 8 variables for the evaluation.

3.  There are 195 female professors.
